language: cpp

arch:
  - amd64
  - ppc64le
  - s390x
  - arm64 

os:
  - linux

dist:
  - focal

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libboost-all-dev

script:
  - ./configure
  - make
  - make test
  - sudo make install
